### ISSUE TITLE
ES metricdef lookups too slow

### ISSUE THREAD

**Issue by Dieterbe** [raintank/graphite-raintank#22]
as https://grafana-monitor.raintank.io/dashboard/db/graphite-api shows, ES metricdef lookups have seen a speed boost around jan 31 (down to 65ms mean), but otherwise have gradually been getting slower over time, and since a while now have been around 200ms mean. the upper 75th percentile has been around 1s for a while, meaning for 25% of requests the delay is >=1s.

metric tank on the other hand, has a mean of 40ms (upto +-- 60ms when running single node) , with a 90th percentile fluctuating between 0.7s and 4s (expected to go down a lot once rollup reading is out)

so if we can make ES requests faster, we can speed up many of the requests significantly. and since graphite-api workers can only do 1 request at a time, we could improve throughput a lot as well.
so i was wondering if there's any low hanging fruit with how we query ES or how it's configured?

emphasis on low hanging fruit: I don't want us to put too much effort into this. having an index in MT (https://github.com/raintank/raintank-metric/issues/178) should bring the metricdef latency down significantly (based on numbers seen in carbonserver and carbonapi)

**Comment by Dieterbe** [comment]
so at this point - if we can trust the graphite-api statsd readings - 200ms median time from ES is pretty much the best case now. there are often periods of several minutes where it's more like median 800ms or more.

@woodsaj @ctdk any input? see these points:
- alerting is normally 150 jobs/s but i've seen it go as low as 75 jobs/s when graphite query times are 800ms
- we have 3 grafana servers with each 2 graphite workers and each worker can only execute 1 request at a time. this would mean during 800ms slowdowns we can only handle 7.5 requests/per second. **i have to be wrong about this, especially given the above**
- either way clearly whenever graphite/ES gets slower, alerting is immediately impacted. user queries probably as well.
- is there any low hanging fruit to speed up graphite or ES? can we do more graphite workers? is ES really this slow or is it graphite not keeping up and the ES timings actually reflect graphite being slow?

either way it looks like having the index in MT may be a good option, this will let us send all alerting traffic to MT, bypassing graphite-api (python) and ES. this alone may make the former much faster if they only have to process user queries.

**Comment by woodsaj** [comment]
to reduce query load we need to add caching to graphite-raintank.  There is no need to be making the same request to ES every 10seconds.

> we have 3 grafana servers with each 2 graphite workers and each worker can only execute 1 request at a time. this would mean during 800ms slowdowns we can only handle 7.5 requests/per second. i have to be wrong about this, especially given the above

Yes, that is wrong.  Graphite is configured to use Eventlet.  So though there are only 2 threads, within those threads can be many greenthreads.  So only 2 requests can concurrently use the CPU but there is no limit on the number of requests that can be handled.  Eventlet is designed for our use case where most of the time the request is IO blocked waiting for a remote service (elasticsearch or metricTank)

The impact seen on alerting is due to request latency, not the number of requests. The drop in alerting queries is due to GrafanaAlerting not sending the queries, it is not because graphite cant handle the load.  This is because each grafana node is configured with 30 goroutines for executing alerting jobs.  However there are >150 jobs per second that need to be run, ~50 per grafana server.  So if each job needs to complete within 1.2seconds else Grafana wont be able to keep up.

The only impact to user queries is that they also will experience the increased latency.

**Comment by Dieterbe** [comment]
the ES machines were maxing out cpu. ct has upgraded the es hardware and we're now getting ~40 ms median times. much better!
